name: test-hls4ml-backend-env
channels:
  - defaults
dependencies:
  - pip=21.0.1
  - python=3.7
  - pip:
    - pyaml
    - blessings==1.7
    - gpustat==0.6.0
    - imageio==2.9
    - nvidia-ml-py3==7.352.0
    - opencv-python==4.5.1.48
    - psutil==5.8.0
    - scipy==1.4
    - protobuf==3.14
    - tensorflow==2.8
    - tensorflow_model_optimization
    - matplotlib
    - tensorboardx==2.1
    - qkeras==0.9.0
    - git+https://github.com/fnal-fastml/hls4ml.git@external-weights-vivado-accelerator#egg=hls4ml[profiling]
